name: Build and Deploy .NET 8 App to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - Deven

env:
  BUILD_CONFIGURATION: Release
  PROJECT_FILE: ./MyApi.csproj
  AZURE_WEBAPP_NAME: myapi-app-ramu

jobs:
# ================= BUILD JOB =================
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build Project
      run: dotnet build ${{ env.PROJECT_FILE }} --configuration ${{ env.BUILD_CONFIGURATION }}

    - name: Publish Project
      run: dotnet publish ${{ env.PROJECT_FILE }} --configuration ${{ env.BUILD_CONFIGURATION }} --output ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop
        path: ./publish 
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: drop
        path: ./downloaded-publish
  deploy:
    runs-on: ubuntu-latest
    needs: build   # Ensures deploy runs after build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: drop
        path: ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
