name: Build and Deploy .NET 8 App to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - Dev

env:
  PROJECT_FILE: ./MyApi/MyApi.csproj

jobs:

# ================= BUILD JOB =================
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore Packages
      run: dotnet restore **/*.sln

    - name: Build Project
      run: dotnet build **/*.sln --configuration $BUILD_CONFIGURATION

    - name: Publish Project
      run: dotnet publish **/*.csproj --configuration $BUILD_CONFIGURATION --output ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop
        path: ./publish
